### ISSUE TITLE
fitINLA output years?

### ISSUE THREAD

**Issue by richardli** [richardli/SUMMER#15]
The years variable is character. The years variable from ``getDirect`` is factor (and is usually used to extract the year levels without typing them out, e.g., when you see ``years = levels(birth$years)`` in vignettes). 

Maybe worth making both factors, is the consistency worth the risk of using factors?

**Comment by Awugchew** [comment]
dear Richard! 
the getDirectList() functin failed to take the regionvar. returns
 Error in getDirect(births = births[[1]], years = years, regionVar = regionVar, : region variable not defined, and no v101 or v024!

**Comment by richardli** [comment]
HI @Awugchew, thank you.  Just move this to a new thread for bookkeeping. Please see my reply at this link: #17
