### ISSUE TITLE
error massage in fitINLA() estimate the Random Walk 2 random effects on the yearly scale

### ISSUE THREAD

**Issue by Awugchew** [richardli/SUMMER#18]
Dear Dr. Z. Richard Li!

while trying to fit direct estimate using fitINLA() function to estimate the Random Walk 2 random effects on the yearly scale, it returns error message. 

fit2 <- fitINLA(data = data, geo = NULL, Amat = NULL, year_label = years.all, 
    year_range = c(1985, 2019), rw = 2, is.yearly = TRUE, m = 5, type.st = 4)

returns:
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 42, 72

**Comment by richardli** [comment]
hi, I'm not sure but suspect years.all is not set correctly. It should contain all the levels in ``data$years``.
