### ISSUE TITLE
No option to set nest=TRUE in the svydesign in fitGeneric

### ISSUE THREAD

**Issue by danfridman** [richardli/SUMMER#19]
I'm using data from a two-stage cluster sample and have some duplicate id's between clusters. To fix this with `svydesign()`, I would just set `nest=T`. There is no option to do that in` fitGeneric()`.

As an aside, is there a reason it is preferable to have to recreate a the svydesign object in the `fitGeneric()` call, rather than just having the option to just reference an existing `svydesign` object?

```
> fitGeneric(data = khi_base, geo = UCmap, Amat = mat, responseType = "binary", 
+            responseVar = "novac", strataVar = "mc_104", weightVar = "dsgnwt", regionVar = "mc_104", 
+            clusterVar = "~mc_105", CI = 0.95)

Error in svydesign.default(ids = stats::formula(clusterVar), weights = ~weights0,  : 
  Clusters not nested in strata at top level; you may want nest=TRUE.
```

**Comment by richardli** [comment]
Hi, thanks, sorry for taking a long time. The feature is added in 82559f891c7ed2cdacec4f776ae8f2e932b12201, now ``nest=TRUE`` (and other svydesign() arguments as well) should be able to be passed into ``svydesign()`` by 
```
fitGeneric(..., nest=TRUE)
```
