### ISSUE TITLE
Issue with the fitGeneric function 

### ISSUE THREAD

**Issue by ifeomaozo** [richardli/SUMMER#21]
Hi there,  I would like to use the summer package, Nigeria DHS 2018, district level to generate SAE for the malaria parasitemia and when I run fitGeneric() to obtain smoothed estimates without weights, 

smoothed <- fitGeneric(data = pfpr_df_2, geo = LGA, Amat = mat, responseType = "binary", 
                       responseVar = "hml32", strataVar = NULL, weightVar = NULL, regionVar = "LGA", 
                       clusterVar = NULL, CI = 0.95)

I get the error 

Error in fitGeneric(data = pfpr_df_2, geo = admin1shp, Amat = mat, responseType = "binary",  : 
  Exist regions in data but not in the Amat.

However, checking the two datasets with the code below, which I think the function is doing (not sure), I see that it is counting the LGA names as 7933. The actual LGA length is 653 in pfpr_df_2 
 and 774 in mat.  I am using the same name formats in both. I am not sure how to fix this. I will appreciate any assistance  

> sum(!pfpr_df_2$LGA %in% colnames(mat))
[1] 7933

**Comment by richardli** [comment]
Hi, I think you should check the names in the data and Amat to be consistent. As a start, probably check the list of names in the two objects:
```
unique(pfpr_df_2$LGA)
```
and
```
colnames(mat)
```
If you see names not matching, you will need to change in the data.
