### ISSUE TITLE
Error when running spatial temporal model using smoothing survey, 

### ISSUE THREAD

**Issue by Cheni-design** [richardli/SUMMER#23]
smooth.year <- smoothSurvey(data =COD_ANC_comb_data, geo = geo,
                             Amat = Amat,  responseType ="binary", responseVar = "anc_timing",
                             strataVar = "residence", weightVar = "sample_weight", regionVar = "region",
                             clusterVar = "~DHSCLUST+caseid",timeVar = "year", time.model="rw2",
                             CI = 0.95, formula=formula1, type.st = 4, nest=TRUE)

**** l get this error below when l run the code below, please help
Error in fit$marginals.linear.predictor[[i]] : subscript out of bounds

**Comment by richardli** [comment]
I need more information to know what is going on. Can you show what is the output of these commands:
```head(COD_ANC_comb_data)```
```colnames(Amat)```
```unique(COD_ANC_comb_data$region)```
```unique(COD_ANC_comb_data$year)```

**Comment by Cheni-design** [comment]
> I need more information to know what is going on. Can you show what is the output of these commands:
> `head(COD_ANC_comb_data)`
> `colnames(Amat)`
> `unique(COD_ANC_comb_data$region)`
> `unique(COD_ANC_comb_data$year)`

 DHSCLUST          caseid country sample_weight     v024 residence anc_timing year
1        1         1  7  4     CD5       1098095 Kinshasa         1          0 2007
2        1         1 19  2     CD5       1098095 Kinshasa         1          1 2007
3        1         1 45  5     CD5       1098095 Kinshasa         1          0 2007
4        1         1 45 13     CD5       1098095 Kinshasa         1          1 2007
5        1         1 77  1     CD5       1098095 Kinshasa         1          1 2007
6        1         1 77  4     CD5       1098095 Kinshasa         1          1 2007
  case_id   region province
1       1 Kinshasa Kinshasa
2       2 Kinshasa Kinshasa
3       3 Kinshasa Kinshasa
4       4 Kinshasa Kinshasa
5       5 Kinshasa Kinshasa
6       6 Kinshasa Kinshasa
> colnames(mat)
 [1] "Bas-Uele"       "Equateur"       "Haut-Katanga"   "Haut-Lomami"   
 [5] "Haut-Uele"      "Ituri"          "Kasai"          "Kasai-Central" 
 [9] "Kasai-Oriental" "Kinshasa"       "Kongo Central"  "Kwango"        
[13] "Kwilu"          "Lomami"         "Lualaba"        "Mai-Ndombe"    
[17] "Maniema"        "Mongala"        "Nord-Kivu"      "Nord-Ubangi"   
[21] "Sankuru"        "Sud-Kivu"       "Sud-Ubangi"     "Tanganyka"     
[25] "Tshopo"         "Tshuapa"       
> unique(COD_ANC_comb_data$region)
 [1] "Kinshasa"       "Nord-Kivu"      "Sud-Kivu"       "Kwango"        
 [5] "Tshopo"         "Kwilu"          "Kasai"          "Maniema"       
 [9] "Ituri"          "Kongo Central"  "Equateur"       "Tanganyka"     
[13] "Haut-Lomami"    "Haut-Katanga"   "Haut-Uele"      "Sud-Ubangi"    
[17] "Kasai-Central"  "Lualaba"        "Lomami"         "Bas-Uele"      
[21] "Tshuapa"        "Mongala"        "Nord-Ubangi"    "Sankuru"       
[25] "Mai-Ndombe"     "Kasai-Oriental"
> unique(COD_ANC_comb_data$year)
[1] 2007 2014

**Comment by richardli** [comment]
Thank you. My best guess is that the issue is because the time variable here. First, the time variable in the `smoothSurvey` function needs to be integer index from 1, 2, .... So in your case, you need to first create variables in that way, instead of using 2007 and 2014. However, a second issue is that with only two time points, the model cannot reliably estimate a time trend. Do you have more data? If not probably worth just fitting the spatial model on the two time points separately.

**Comment by Cheni-design** [comment]
> Thank you. My best guess is that the issue is because the time variable here. First, the time variable in the `smoothSurvey` function needs to be integer index from 1, 2, .... So in your case, you need to first create variables in that way, instead of using 2007 and 2014. However, a second issue is that with only two time points, the model cannot reliably estimate a time trend. Do you have more data? If not probably worth just fitting the spatial model on the two time points separately.

Thank you, one question how do l check which model is the best e.g spatio temporal models where one has a type 11 interaction and the other has a type iv interaction
