### ISSUE TITLE
Error message on Exist regions in data but not in the Amat using the BRFSS data

### ISSUE THREAD

**Issue by Cheni-design** [richardli/SUMMER#24]
svysmoothed.year <- smoothSurvey(data = BRFSS, geo = KingCounty, Amat = mat,
+                                  responseType = "binary", responseVar = "diab2", strataVar = "strata", weightVar = "rwt_llcp",
+                                  regionVar = "hracode", clusterVar = "~1", timeVar = "year", time.model = "rw1",
+                                  type.st = 1)
Error in smoothSurvey(data = BRFSS, geo = KingCounty, Amat = mat, responseType = "binary",  : 
  Exist regions in data but not in the Amat.

**Comment by richardli** [comment]
Hi I believe you are following an old tutorial with out-dated codes leading up to this error. Try the example here: https://cran.r-project.org/web/packages/SUMMER/vignettes/summer-vignette.html

**Comment by Cheni-design** [comment]
Yes thank you,  l have seen the updated example but it does not include the time component in the last code below, which l have a particular interest in. My outcome is binary and is similar to the example in the BRFSS data. I would like to measure the spatio- temporal component which factors times of different survey years.

formula <- "f(region.struct, model = 'besag', graph = Amat, 
                constr = TRUE, scale.model = TRUE) + 
             f(region.unstruct, model = 'iid')"
 svysmooth.2 <- smoothSurvey(data = BRFSS, geo = KingCounty, Amat = mat, 
  responseType = "binary", responseVar="diab2", 
  strataVar="strata", weightVar="rwt_llcp", regionVar="hracode", 
  clusterVar = "~1",   CI = 0.95, 
  formula = formula)

**Comment by richardli** [comment]
Thank you, I believe it is the same question as in issue #23. Let's discuss under that thread and I'll close this issue here. But feel free to comment here if I'm missing anything in your questions.
