### ISSUE TITLE
Error when running spatial model using smoothSurvey

### ISSUE THREAD

**Issue by mohdrejab** [richardli/SUMMER#29]
Hi, 

I got this error message when running the codes below: 

smoothed <- smoothSurvey(data = data, geo = districts, Amat = mat, 
            responseType = "binary", responseVar = "OW", strataVar = NULL, weightVar = NULL,
            regionVar = "district", clusterVar = NULL, CI = 0.95)
summary(smoothed)

>> Strata not defined. Ignoring sample design
>> cluster not specified. Ignoring sample design
>> Error in fit$marginals.linear.predictor[[i]] : subscript out of bounds

There was no problem when running the weighted and smoothed estimates with the codes below. 

svysmoothed <- smoothSurvey(data = data, geo = districts, Amat = mat, 
              responseType = "binary", responseVar="OW", strataVar = "PSU",  weightVar ="Weight_Final", 
              regionVar ="district", clusterVar = "~1", CI = 0.95)
summary(svysmoothed)

I really appreciate your help. Thank you.

**Comment by richardli** [comment]
Hi, 

I am not able to reproduce the error with another dataset. So I suspect something is incorrect with the data. The following codes is what I tried with the similar arguments as you specified, and it runs fine. 

```
library(SUMMER)
data(DemoData2)
data(DemoMap2)
fit0 <- smoothSurvey(data=DemoData2,
				Amat=DemoMap2$Amat, 
                                  responseType="binary",
				responseVar="tobacco.use",
				strataVar = NULL,
				weightVar = NULL,
				clusterVar = NULL, CI = 0.95,
				regionVar = "region")
```

I would double check the data, and get the latest version of SUMMER from github and try again. Let me know if the error persists.

**Comment by mohdrejab** [comment]
Hi,

Thank you for your feedback. I followed your suggestion and double checked both the survey data and the shapefile. I have recoded some of the integer variables into factor variables to be in similar forms as in DemoData2 and DemoMap2. But the error still persists. 

I really appreciate your help. Many thanks again.

**Comment by richardli** [comment]
Hi, 

If you could share a script and data file that reproduce the error, could you send to lizehang@gmail.com? Then I can take a look into the error.

**Comment by mohdrejab** [comment]
Hi, 

I had sent a script and the data file to your email. Thank you very much for your time.

**Comment by mohdrejab** [comment]
Hi, 
I am just wondering if you have received the email which contains the data file that I had sent to you earlier (my email address is zainirejab at gmail). If not, kindly let me know as I will resend the email together with the data file. Thank you for your time.

**Comment by richardli** [comment]
Hi, 
I was only able to replicate the issue this week, which seems to be due to a default option change in INLA. The latest version of SUMMER 1.2.1 should have fixed this issue. Let me know if it persists.
