### ISSUE TITLE
vignette error

### ISSUE THREAD

**Issue by tyokota** [richardli/SUMMER#6]
Aloha!

I am currently running through the vignette, and I am running into the following error:
```

fit2 <- fitINLA(data = data, geo = NULL, Amat = NULL, year_names = years.all,
year_range = c(1985, 2019), priors = priors, rw = 2,
is.yearly=TRUE, m = 5)

Error in exists("my.cache", envir = envir, mode = "list") : 
  use of NULL environment is defunct
```
I am running R 3.5.1 on Windows.

**Comment by richardli** [comment]
Hi, I couldn't replicate this error in my mac. So I guess it's something to do with your R session or R version on Windows. Can you double check again and let us know if the error persists? And if so can you start a clean R session and try again? 

If it still can't run, can you send us the output from ```sessionInfo()``` and ```traceback()```?
