### ISSUE TITLE
Error in vignette 

### ISSUE THREAD

**Issue by ifeomaozo** [richardli/SUMMER#7]
Hi, I followed the tutorial in the vignette and observed the newformula as seen below was commented out but I tried to use it anyway since you used the penalized complexity priors and I wanted to see how the result differed from the default priors. However, Amat in the "graph=Amat" was not previously defined and so I replaced it with "mat" which has used to define the adjacency matrix previously but my results differed (see attachment) The code below is from the vignette. 

`newformula <- "f(region.struct, model = 'bym2', graph = Amat,
constr = TRUE,scale.model = TRUE, hyper = list(
phi = list(prior = 'pc', param = c(0.5 , 2/3)
, initial = -3),
prec = list(prior = 'pc.prec', param = c(0.2/0.31 , 0.01)
, initial = 5)))"
svysmooth.2 <- fitSpace(data = BRFSS, geo = KingCounty, Amat = mat,
family = "binomial", responseVar="diab2",
strataVar="strata", weightVar="rwt_llcp", regionVar="hracode",
clusterVar = "~1", hyper=NULL, CI = 0.95,
newformula = newformula)`

`Error in f(region.struct, model = "bym2", graph = Amat, constr = TRUE,  : 
  object 'Amat' not found
In addition: Warning message:
In inla.model.properties.generic(inla.trim.family(model), (mm[names(mm) ==  :
  Model 'bym2' in section 'latent' is marked as 'experimental'; changes may appear at any time.
  Use this model with extra care!!! Further warnings are disabled.`

I replaced graph = Amat with graph = mat and it worked. Problem is my results were different for the PC prior 

`svysmooth.2 <- fitSpace(data = BRFSS, geo = KingCounty, Amat = mat,
                        family = "binomial", responseVar="diab2",
                        strataVar="strata", weightVar="rwt_llcp", regionVar="hracode",
                        clusterVar = "~1", hyper=NULL, CI = 0.95,
                        newformula = newformula)`

![rplot](https://user-images.githubusercontent.com/21004206/53829625-91f0ff00-3f4e-11e9-912b-8f8ae2ff64c3.jpeg)

**Comment by richardli** [comment]
Thank you for posting. In this example, ```Amat``` refers to the argument ```Amat``` in the ```fitSpace()``` function. So you should use Amat without changing it, since inside the function, there are additional bookkeepings that make Amat consistent with data. 

But I agree, the current interface is a little confusing. We'll think of a better way to specify models in the next release.

**Comment by richardli** [comment]
Forgot to answer the first part: I reran your original codes and it works for me without error. See the following:

```
library(SUMMER)
data(BRFSS)
data(KingCounty)
BRFSS <- subset(BRFSS, !is.na(BRFSS$diab2))
BRFSS <- subset(BRFSS, !is.na(BRFSS$hracode))
library(spdep)
nb.r <- poly2nb(KingCounty, queen=F, 
    row.names = KingCounty$HRA2010v2_)
mat <- nb2mat(nb.r, style="B",zero.policy=TRUE)
colnames(mat) <- rownames(mat) 
mat <- as.matrix(mat[1:dim(mat)[1], 1:dim(mat)[1]])


newformula <- "f(region.struct, model = 'bym2', graph = Amat, constr = TRUE,scale.model = TRUE, hyper = list( phi = list(prior = 'pc', param = c(0.5 , 2/3) , initial = -3), prec = list(prior = 'pc.prec', param = c(0.2/0.31 , 0.01) , initial = 5)))" 

svysmooth.2 <- fitSpace(data = BRFSS, geo = KingCounty, Amat = mat, family = "binomial", responseVar="diab2", strataVar="strata", weightVar="rwt_llcp", regionVar="hracode", clusterVar = "~1", hyper=NULL, CI = 0.95, newformula = newformula)

mapPlot(data = svysmooth.2$smooth, geo = KingCounty, variables=c("mean.original"), labels = c("Posterior mean (PC prior)"), by.data = "region", by.geo = "HRA2010v2_")  
```

**Comment by ifeomaozo** [comment]
Thank you! I see now that the quotes does not mean that it is commented out.

**Comment by richardli** [comment]
Hah no problem at all!
