### ISSUE TITLE
fitINLA2 requires data frame with no survey variable

### ISSUE THREAD

**Issue by jlgodwin** [richardli/SUMMER#9]
We need to make sure when using data from multiple surveys that the $cluster columns values are unique by survey. It's probably best to have people submit a data.frame with one extra column: $surveyyear so that internally unique IDs for clusters can be specified in a new cluster column and we can figure out how to combine across surveys

**Comment by jlgodwin** [comment]
> We need to make sure when using data from multiple surveys that the $cluster columns values are unique by survey. It's probably best to have people submit a data.frame with one extra column: $surveyyear so that internally unique IDs for clusters can be specified in a new cluster column and we can figure out how to combine across surveys

On further look at the code, it appears you take care of this but the documentation does not mention a $survey variable

**Comment by richardli** [comment]
thank you! yes it's a good catch indeed. I haven't added survey effects yet, so that part is a bit half-done. But will keep this in mind!

**Comment by richardli** [comment]
@jlgodwin sorry for the long delay: e9c18255d4bfcc should have solved this. Now there can be a survey iid random effect (using the new argument ``fitINLA2(..., survey.effect = TRUE)``. If ``survey.effect`` is set to false, the survey column will be ignored (and should be fine with or without a survey column).

**Comment by richardli** [comment]
And for the binomial model where cluster ID matters, updated here:  05dc316
